//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.05 at 02:41:12 AM IST 
//


package com.sapgcp.xml.sar;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sapgcp.xml.sar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sapgcp.xml.sar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SARReport }
     * 
     */
    public SARReport createSARReport() {
        return new SARReport();
    }

    /**
     * Create an instance of {@link SARReport.DataMap }
     * 
     */
    public SARReport.DataMap createSARReportDataMap() {
        return new SARReport.DataMap();
    }

    /**
     * Create an instance of {@link FolderRequest }
     * 
     */
    public FolderRequest createFolderRequest() {
        return new FolderRequest();
    }

    /**
     * Create an instance of {@link SARRequest }
     * 
     */
    public SARRequest createSARRequest() {
        return new SARRequest();
    }

    /**
     * Create an instance of {@link SARResponse }
     * 
     */
    public SARResponse createSARResponse() {
        return new SARResponse();
    }

    /**
     * Create an instance of {@link FolderResponse }
     * 
     */
    public FolderResponse createFolderResponse() {
        return new FolderResponse();
    }

    /**
     * Create an instance of {@link SARReport.DataMap.Entry }
     * 
     */
    public SARReport.DataMap.Entry createSARReportDataMapEntry() {
        return new SARReport.DataMap.Entry();
    }

}
