//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.05 at 02:41:12 AM IST 
//


package com.sapgcp.xml.sar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SARReport" type="{http://www.sapgcp.com/xml/sar}SARReport"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sarReport"
})
@XmlRootElement(name = "SARRequest")
public class SARRequest {

    @XmlElement(name = "SARReport", required = true)
    protected SARReport sarReport;

    /**
     * Gets the value of the sarReport property.
     * 
     * @return
     *     possible object is
     *     {@link SARReport }
     *     
     */
    public SARReport getSARReport() {
        return sarReport;
    }

    /**
     * Sets the value of the sarReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link SARReport }
     *     
     */
    public void setSARReport(SARReport value) {
        this.sarReport = value;
    }

}
